### ISSUE TITLE
Build fails : multiple definition of "start_plugins()"

### ISSUE THREAD

**Issue by snowshow** [andig/vzero#2]
@andig 
There is a double definition of start_plugins() function:

https://github.com/andig/vzero/blob/4d5f774a1ea5f095cedaa825d71bf259290e87c9/config.cpp#L185
https://github.com/andig/vzero/blob/4d5f774a1ea5f095cedaa825d71bf259290e87c9/vzero.ino#L172

**Comment by andig** [comment]
Fixed.
